name: cooktalk_mvc
description: CookTalk Flutter MVC prototype
environment:
  sdk: ">=3.0.0 <4.0.0"

publish_to: "none"
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.2
  url_launcher: ^6.3.0
  file_picker: ^8.0.0
  google_generative_ai: ^0.4.7
  youtube_explode_dart: ^2.0.0
  flutter_dotenv: ^5.1.0
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.0
  flutter_local_notifications: ^18.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.13.0
  shared_preferences: ^2.2.2
  flutter_tts: ^4.0.2
  
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  google_sign_in: ^6.2.1
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.3.0
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

